### ISSUE TITLE
Persian dataset

### ISSUE THREAD

**Issue by MohammadRoodbari** [majidAdibian77/persian-SV2TTS#1]
Can you share the dataset?!

**Comment by Adibian** [comment]
Hi
We used a new multi-speaker dataset described in [this paper](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4530203).
You can email the second author of this paper (who is the owner of this data), request this dataset, and find out whether it is freely available or not.

**Comment by MohammadRoodbari** [comment]
Greetings,

I need this dataset to retrain the model.
Better choice is to use pretrained model.
Can you please send me the encoder, decoder and synthesizer weight of your
model?
